# Generated by Django 6.1.1 on 2026-09-29 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('address', models.CharField(help_text='Highway and exit, as in the price file', max_length=160)),
                ('city', models.CharField(max_length=80)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('country', models.CharField(default='US', max_length=2)),
                ('rack_id', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=4, help_text='Dollars per gallon used for planning', max_digits=7)),
                ('price_min', models.DecimalField(decimal_places=4, max_digits=7)),
                ('price_max', models.DecimalField(decimal_places=4, max_digits=7)),
                ('price_rows', models.PositiveSmallIntegerField(default=1)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('geo_source', models.CharField(blank=True, help_text='How the city centroid was found', max_length=24)),
            ],
            options={
                'ordering': ['state', 'city', 'name'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='stations_st_latitud_ba98b4_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gt', 0)), name='station_price_positive'), models.CheckConstraint(condition=models.Q(models.Q(('latitude__isnull', True), ('longitude__isnull', True)), models.Q(('latitude__isnull', False), ('longitude__isnull', False)), _connector='OR'), name='station_coordinates_all_or_none')],
            },
        ),
    ]
